# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.0.1
_src_path: https://github.com/napari/napari-plugin-template
display_name: pyVertexModel
email: p.munuera@ucl.ac.uk
full_name: Pablo Vicente-Munuera
github_repository_url: https://github.com/pablo1990/napari-pyvertexmodel
github_username_or_organization: pablo1990
include_reader_plugin: true
include_sample_data_plugin: true
include_widget_plugin: true
include_writer_plugin: true
install_dependabot: true
install_precommit: true
license: GNU GPL v3.0
module_name: napari_pyvertexmodel
plugin_name: napari-pyvertexmodel
short_description: Run 3D mechanical simulations with pyVertexModel
