"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/building_a_plugin/guides.html#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""
from typing import TYPE_CHECKING

import numpy as np
from magicgui import magic_factory
from magicgui.widgets import CheckBox, Container, create_widget
from qtpy.QtWidgets import QHBoxLayout, QPushButton, QWidget
from skimage.util import img_as_float
from pyvertexmodel.algorithm.vertexModelVoronoiFromTimeImage import VertexModelVoronoiFromTimeImage
from pyvertexmodel.util.utils import load_state
from vtkmodules.util.numpy_support import vtk_to_numpy

if TYPE_CHECKING:
    import napari

# magicgui `Container`
class Run3dVertexModel(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self._viewer = viewer
        # use create_widget to generate widgets from type annotations
        self._load_simulation_button = create_widget(
            label="Load Simulation", annotation=str, widget_type="FileEdit"
        )
        self._image_layer_combo = create_widget(
            label="Input Labels", annotation="napari.layers.Labels"
        )
        self._threshold_slider = create_widget(
            label="Threshold", annotation=float, widget_type="FloatSlider"
        )
        self._threshold_slider.min = 0
        self._threshold_slider.max = 1
        # use magicgui widgets directly
        self._invert_checkbox = CheckBox(text="Keep pixels below threshold")

        # Add button to run Vertex Model
        self._run_button = QPushButton("Run it!")

        # connect your own callbacks
        self._run_button.clicked.connect(self._run_model)
        self._load_simulation_button.connect(self._load_simulation)

        # append into/extend the container with your widgets
        self.extend(
            [
                self._image_layer_combo,
                self._threshold_slider,
                self._invert_checkbox,
                self._run_button,
                self._load_simulation_button,
            ]
        )

    def _run_model(self):
        image_layer = self._image_layer_combo.value
        if image_layer is None:
            return
        try:
            # Create Vertex Model
            vModel = VertexModelVoronoiFromTimeImage(create_output_folder=False, set_option='wing_disc_equilibrium')

            # Initialize model
            vModel.initialize()
            # Run the simulation
            vModel.iterate_over_time()

            # Save image to viewer
            self._add_surface_layer(vModel)
        except Exception as e:
            print(f"An error occurred while running the Vertex Model: {e}")

    def _load_simulation(self):
        file_path = self._load_simulation_button.value
        if not file_path:
            return
        try:
            # Load the simulation state
            vModel = VertexModelVoronoiFromTimeImage(create_output_folder=False, set_option='wing_disc_equilibrium')
            load_state(vModel, file_path)

            # Save image to viewer
            self._add_surface_layer(vModel)
        except Exception as e:
            print(f"An error occurred while loading the simulation: {e}")

    def _add_surface_layer(self, vModel):
        """
        Add surface layer to napari viewer
        :param vModel:
        :return:
        """
        layer_name = vModel.model_name

        for cell_id, c_cell in enumerate(vModel.geo.Cells):
            layer_name_cell = f"{layer_name}_cell_{c_cell.ID}"
            vtk_poly = c_cell.create_vtk()
            t_vertices = vtk_to_numpy(vtk_poly.GetPoints().GetData())
            t_faces = vtk_to_numpy(vtk_poly.GetPolys().GetData()).reshape(-1, 4)[:, 1:4]
            t_scalars = vtk_to_numpy(vtk_poly.GetScalars()).astype(np.float32)
            try:
                # if the layer exists, update the data
                curr_verts, curr_faces, curr_values = self.viewer.layers[
                    layer_name_cell
                ].data

                self.viewer.layers[layer_name_cell].data = (
                    np.concatenate((curr_verts, t_vertices), axis=0),
                    np.concatenate((curr_faces, t_faces), axis=0),
                    np.concatenate((curr_values, t_scalars), axis=0),
                )

                # Update timepoint that is displayed
                self.viewer.dims.set_current_step(0, vModel.t)

            except KeyError:
                # otherwise add it to the viewer
                self.viewer.add_surface(
                    (t_vertices, t_faces, t_scalars),
                    colormap="viridis",
                    opacity=0.9,
                    contrast_limits=[0, 1],
                    name=layer_name,
                )

